version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/ME-CSE-Project-

permissions:
  - object: /home/ubuntu/ME-CSE-Project-
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu